version: "3.8"
services:
  movies:
    image: layareddy14/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: layareddy14/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: layareddy14/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: layareddy14/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

~
